clip_1:
  vts_video_file: /files/master_files/example/the_compassionate_father_1.mp4
  local_image_file: /img/clips/clip_1.jpg
  text: 'One day, Jesus was teaching many tax collectors and sinners who were with him.'
clip_2:
  vts_video_file: /files/master_files/example/the_compassionate_father_2.mp4
  local_image_file: /img/clips/clip_2.jpg
  text: 'The religious leaders were grumbling because Jesus was treating these people as friends. So Jesus told this story.'
clip_3:
  vts_video_file: /files/master_files/example/the_compassionate_father_3.mp4
  local_image_file: /img/clips/clip_3.jpg
  text: '"There was a man who had two sons. The younger son told his father, "Father, I want my inheritance now!" So the father divided his property between the two sons.'
clip_4:
  vts_video_file: /files/master_files/example/the_compassionate_father_4.mp4
  local_image_file: /img/clips/clip_4.jpg
  text: 'Soon the younger son sold all that he had and went far away and wasted his money in sinful living.'
clip_5:
  vts_video_file: /files/master_files/example/the_compassionate_father_5.mp4
  local_image_file: /img/clips/clip_5.jpg
  text: "At that time a severe famine came on the land and he had no money to buy food. So he took the only job he could find, feeding pigs. He was so miserable and hungry that he wanted to eat the pigs' food."
clip_6:
  vts_video_file: /files/master_files/example/the_compassionate_father_6.mp4
  local_image_file: /img/clips/clip_6.jpg
  text: "Finally the younger son said to himself, 'What am I doing? All my father's servants have plenty to eat and yet here I am starving. I will go back to my father and ask to be one of his servants.'"
clip_7:
  vts_video_file: /files/master_files/example/the_compassionate_father_7.mp4
  local_image_file: /img/clips/clip_7.jpg
  text: 'While the younger son was still far away, his father saw him and felt compassion for him. He ran to his son and hugged him and kissed him.'
clip_8:
  vts_video_file: /files/master_files/example/the_compassionate_father_8.mp4
  local_image_file: /img/clips/clip_8.jpg
  text: "The son said, 'Father, I have sinned against God and against you. I am not worthy to be your son, let me be your servant instead.'"
clip_9:
  vts_video_file: /files/master_files/example/the_compassionate_father_9.mp4
  local_image_file: /img/clips/clip_9.jpg
  text: "But his father told one of his servants, 'Go quickly! Bring the best clothes and put them on my son! Put a ring on his finger and put sandals on his feet. Then kill the best calf so we can have a feast, because my son was dead, but now he is alive! He was lost but now he is found!'"
clip_10:
  vts_video_file: /files/master_files/example/the_compassionate_father_10.mp4
  local_image_file: /img/clips/clip_10.jpg
  text: "And they began to celebrate. Before long, the older son came home from working in the field. He heard the music and dancing and wondered what was happening."
clip_11:
  vts_video_file: /files/master_files/example/the_compassionate_father_11.mp4
  local_image_file: /img/clips/clip_11.jpg
  text: "When he found out that there was a party because his brother had come home, he was very angry and would not go into the house. His father came out and begged him to join the party, but he refused and said,"
clip_12:
  vts_video_file: /files/master_files/example/the_compassionate_father_12.mp4
  local_image_file: /img/clips/clip_12.jpg
  text: "All these years I've worked so faithfully for you! I never disobeyed you, and still you did not even give me one small goat so I could celebrate with my friends. But when this son of yours wastes your money on sinful behavior you kill the best calf for him!'"
clip_13:
  vts_video_file: /files/master_files/example/the_compassionate_father_13.mp4
  local_image_file: /img/clips/clip_13.jpg
  text: "The father answered, 'My son, you are always with me, and everything I have is yours. But it is right for us to celebrate, because your brother was dead, but now is alive. He was lost, but now is found!'"